### PR TITLE
SSINS pipeline update

### PR DESCRIPTION
**Pull request by mwilensky768**
In this PR I'm trying to stick SSINS in the rtp for h3c and h4c. This version should now be able to use file chunking for reasonable outputs. I put it near the beginning in the actions list just because it is typically run on uncalibrated visibilities. Willing to iterate on this. Tested this on my local machine in a toml using just SSINS that was removed in one of the commits here. Did seem to work on my local machine. Have not tested how it plays with the whole pipeline.

### CODE REVIEW

**Comment by jsdillon** [comment]
Thanks for this @mwilensky768.

Two things: 
1) can we hold off changes to the h4c pipeline on the master branch until I'm done testing that it work? I'm debugging right now.
2) until #102 is addressed, I'd like to avoid adding things to the middle of a workflow, since if they break it stops the rest of the pipeline from going forward.

**Comment by mwilensky768** [comment]
No problem @jsdillon 

Just wanted this to be in place so that people can see SSINS as soon as wanted/reasonable.

**Comment by plaplant** [comment]
@mwilensky768 just so you're aware, we've moved the pipelines folder to a separate repo: https://github.com/HERA-Team/hera_pipelines. So I don't think this PR would make sense to merge anymore, because the pipeline folder is now gone. I'm closing this PR for now, but I'll keep the branch around in case you wanted to copy any of this over to the new repo.

**Comment by jsdillon** [comment]
FYI, I already pulled some of this (for H4C RTP Stage 1 and H3C IDR3) into `main` on hera_pipelines.

**Pull request closed without merging**
