### PR TITLE
Imaging Step

### PR DESCRIPTION
**Pull request by nkern**
Adds an IMAGING step to h1c/idr2/v2 workflow

### CODE REVIEW

**Comment by nkern** [comment]
@jsdillon Just FYI this is a first pass at adding an IMAGING step at the end of the pipe. To get this working I need a few things from @plaplant 
1) Need to resolve this issue on a `pyuvdata` PR on the `convert_to_uvfits` branch
2) Need to be able to parse the `data_file` suffix and replace it with `.uvfits` in the `do_IMAGING.sh` in shell (which I don't know how to do offhand) and to erase the output of the script, which is a copy of the data as both a `.uvfits` and `.ms` file

then we should be good to go..

**Comment by jsdillon** [comment]
Thanks for getting this started. I think we want to move the script you're using out of your personal folder and into hera_cal or another repo. (Related, I do mean to make OPM stop referencing my folders and start reference heramgr before we do any long runs.)

**Comment by nkern** [comment]
Actually if you look its not a personal script, its a script in `casa_imaging` package, its just pointed to where I have it installed.

**Comment by jsdillon** [comment]
Ah, cool. We should probably get casa installed on heramgr before we do idr2.2, but that shouldn't be too much work.

**Comment by jsdillon** [comment]
@nkern a few questions:

1) Can you update these scripts to also take in calibration solutions. Presumably we'd want this code to be able to work on uncalibrated data by passing in calfits files too.

2) @plaplant says that the pyuvdata issues have been resolved. What else is left to do to get this integrated into the pipeline?

3) Can you help me get this into the omnigraffle? What will the outputs look like? Do we want to run this after XRFI and smooth_cal, or do we want to run it at some point earlier in the pipeline?

**Comment by nkern** [comment]
@jsdillon @plaplant so I think I'm happy with this now. once we test it on real data I'm sure there will be things we can iterate on. feel free to merge it whenever.

**Pull request merged**
